source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'CocoaChinaPlus' do

    #pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    pod 'GodEye', '~> 1.0.0', :configurations => ['Debug']

    pod 'Log4G'
    pod 'AppBaseKit', '~> 0.1.0'
    pod 'SwViewCapture', '~> 1.0.5'
    pod 'Neon', '~> 0.4.0'
    pod 'SwiftyUserDefaults', '~> 3.0.0'
    pod 'Ji', '~> 2.0.1'
    pod 'Kingfisher', '~> 3.2.4'
    pod 'Alamofire', '~> 4.3.0'
    pod 'RxSwift', '~> 3.1.0'
    pod 'RxCocoa', '~> 3.1.0'
    pod 'SQLite.swift', '~> 0.11.2'
    pod 'R.swift', '~> 3.2.0'
    #OC库
    pod 'SVPullToRefresh', '0.4.1'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'UMengAnalytics', '~> 3.5.10'
    pod 'UMengUShare', '~> 6.2.2'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
