source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

pod 'ZXKit', git: 'https://github.com/zixun/ZXKit.git' # '~> 0.0.2'

pod 'Neon', '~> 0.0.2'
pod 'SwiftyUserDefaults', '~> 2.0.0'
pod 'Ji', '~> 1.2.0'
pod 'Kingfisher', '~> 1.8.2'
pod 'Alamofire', '~> 2.0.0'
pod 'RxSwift', '~> 2.0.0-beta.2'
pod 'RxCocoa', '~> 2.0.0-beta.2'
pod 'RxBlocking', '~> 2.0.0-beta.2'
pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git'
pod 'SQLiteCipher.swift', git: 'https://github.com/stephencelis/SQLite.swift.git'

#OC库
pod 'SVPullToRefresh', '0.4.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'UMengAnalytics', '~> 3.5.10'